apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator-python
  namespace: demo-app
spec:
  template:
    spec:
      containers:
        - name: load-generator
          image: frnn4268/k8s-load-generator-python:PRODUCTION_VERSION
