apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-golang
  namespace: demo-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: api-golang
          image: frnn4268/k8s-api-golang:PRODUCTION_VERSION
