targets:
  - name: staging
    args:
      environment: staging
      environmentType: non-prod
    # Adding a context to .kluctl.yaml helps prevent accidentally deploying to the wrong cluster!
    context: devops-3tierwebapp

  - name: production
    args:
      environment: production
      environmentType: prod
    # Adding a context to .kluctl.yaml helps prevent accidentally deploying to the wrong cluster!
    context: gke_kubernetes-424917_us-central1-a_devops-3tierwebapp-2

args:
  - name: environment
  - name: environmentType

discriminator: kluctl-{{ target.name }}
