apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-react-nginx
  namespace: demo-app
spec:
  template:
    spec:
      containers:
        - name: client-react-nginx
          image: frnn4268/k8s-client-react-nginx:PRODUCTION_VERSION
